### ISSUE TITLE
attrs() are no longer merged in v4

### ISSUE THREAD

**Issue by austin94** [styled-components/styled-components#2270]
## Description

👋 Hello. I've been investigating a migration from `v3` to `v4` and have been seeing some different results with the `.attrs()` method while extending other `styled-components`.

Within our component library we have several styled components that use CSS classes applied via the `attrs()` method. [Example](https://github.com/zendeskgarden/react-components/blob/master/packages/tags/src/views/Tag.js)

We also have components that "wrap" (not using the `.extend()` API) to apply additional classNames.

```jsx
const Tooltip = styled.div.attrs({ className: 'tooltip' })``;
const LightTooltip = styled(Tooltip).attrs({ className: 'tooltip--light' })``;
```

In `v4` it doesn't seem that this type of `attrs()` merging is possible. Doesn't seem to be possible even with a `.attrs(props => ({}))` callback. Is this expected?

It seems some attributes are shallow merged (like `styles` in #1877). Should this have the same treatment if it's a common pattern?

## Environment

CodeSandbox default `create-react-app` environment.

## Reproduction

* `styled-components@3.4.10` with `attr` merging
  * https://codesandbox.io/s/o52l69rkwy
* `styled-components@4.1.2` without `attr` merging
  * https://codesandbox.io/s/z2k437v4r3

## Steps to reproduce

1. Create a styled-component with a `className` provided via the `attrs()` method
1. Create another styled-component that wraps the original component `styled(InnerComponent)` which also provides a `className` via the `attrs()` method
1. Only the outer className is being provided.

## Expected Behavior

Similar to `v3` of styled-components, the attrs are merged if a component is extended.

## Actual Behavior

Only the outer `attrs()` methods are respected.

**Comment by mxstbr** [comment]
Huh this is very interesting—I'm not sure why we merged `attrs` like that before! I don't think we should be doing that, as you should manually be opting into letting an attribute being overriden, so I think the behavior in v4 is correct.

If you think about it, if we always automatically merge you can't turn off the lower-level className, which is probably not what you want. Right now, your lower-level component basically has to explicitly allow overriding the attr, which is exactly what `attrs` is for

**Comment by austin94** [comment]
> I don't think we should be doing that, as you should manually be opting into letting an attribute being overriden, so I think the behavior in v4 is correct

Agreed! I'm assuming the behavior worked for us since we were using the `styled(Component)``` syntax rather than `Component.extend```.

> Right now, your lower-level component basically has to explicitly allow overriding the attr, which is exactly what attrs is for

Is there a "best" approach to reliably allow `className` to be overridden in the lower component? I've updated the [v4 Codesandbox](https://codesandbox.io/s/z2k437v4r3) to include another example with the new props callback in `attrs()` and I'm still unable to get `className` to be provided.

```
export const InnerComponent = styled.div.attrs(props => ({
  className: classNames(props.className, "component-inner")
}))``;

export const OuterComponent = styled(InnerComponent).attrs({
  className: "component-outer"
})``;
```

**Comment by oomathias** [comment]
Because `attrs` doesn't work this way (see discussion here https://github.com/styled-components/styled-components/pull/2258)

https://codesandbox.io/s/wyvljmw4k7 works starting from `4.1.2`

**Comment by austin94** [comment]
That makes much sense! Thanks for the diagram at the end of #2258 

Thanks for the help. Closing.

**Comment by three60five** [comment]
I'd vote for this to be reopened. This change really makes the DX for using something like Tachyons or TailwindCSS that much worse. I've loved mixing Tachyons and Styled Components ever since `attrs` were introduced. 

I can write a simple component like 
```
export const TextLink = styled.a.attrs({
  className: 'no-underline bb nowrap',
})`
  padding-bottom: 0.2rem;
  border-color: ${props => props.theme.c30};
  color: ${props => props.theme.c50};
  &:hover {
    cursor: pointer;
    color: ${props => props.theme.blue};
    border-color: ${props => props.theme.blue};
  }
`;
```
and then if I need to bespoke style it, I would just append new classes on to it like so:
```
const DifferentTextLink = styled(TextLink).attrs({
  className: 'f6',
})`
  color: ${props => props.theme.c80};
`;
```

Since the appended classes would come after the first classes, I could also override classes provided through `attrs` this way as well. 

I think the new paradigm is a significant step backward as far as DX for using `attrs`.
