### ISSUE TITLE
styled-components now requires a __SERVER__ global in v5.2.0

### ISSUE THREAD

**Issue by wagoid** [styled-components/styled-components#3284]
Hi there! It appears that on v5.2.0 there was a change that made `styled-components` require that the projects using it start adding the `__SERVER__` global variable in order to make it work. The change was done in [this commit](https://github.com/styled-components/styled-components/commit/f12b943658a9731ab6af6548a780019f696a09cb).

The browser bundle (`dist/styled-components.browser.esm.js`) now requires that we configure this global. This seems like a breaking change that shouldn't be shipped in a Minor bump, right?

## System:
 - OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 775.47 MB / 15.49 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
 - Yarn: 1.21.1 - ~/.yvm/shim/yarn
 - npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.2.0 

## Steps to reproduce
1. Create a project that doesn't have the `__SERVER__` global defined in the build tool's (e.g. webpack) config
2. Import styled-components library in the server side

## Expected Behavior

It should not try to access the `window`.

## Actual Behavior

It tries to access the `window` and breaks.

**Comment by kitten** [comment]
This global has existed for several versions and hasn't been newly added (as seen in the commit)

It's supposed to be compiled away though in our release bundles:
https://github.com/styled-components/styled-components/blob/e0286a105c4921634c7605222d960d79d69ffcc9/packages/styled-components/rollup.config.js#L137

It's possible that this has broken however, if the constant still ends up as a global in the output.

**Comment by nuwan-dammika** [comment]
HI @kitten 

Do you have a way to set `__SERVER__` , its hard-coded in rollup.config right

Thanks

**Comment by kitten** [comment]
Closing due to inactivity.

Please don't forget to be a good netizen on GitHub and revisit issues, especially ones that have been resolved and need to be closed, or ones that have received replies ❤️

**Comment by wagoid** [comment]
Hey @kitten! Sorry for that, since you mentioned that it was possible that this has broken, I thought you were going to investigate the build config.

I have double checked, and it seems like the issue still persists? And from the thumbs up it seems to have affected other people too.

If I open the `dist/styled-components.browser.esm.js` file on [v5.3.0](https://unpkg.com/styled-components@5.3.0/dist/styled-components.browser.esm.js) file I can see a piece of code like the following:
```js
"production"!==process.env.NODE_ENV&&"test"!==process.env.NODE_ENV&&(window["__styled-components-init__"]=window["__styled-components-init__"]||0[...]
```

Now when opening the same file on [v5.1.1](https://unpkg.com/styled-components@5.1.1/dist/styled-components.browser.esm.js), I can find a line with the same intention, but it has a `typeof window` check on it too:
```js
if (process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'test' && typeof window !== 'undefined') {
  window['__styled-components-init__'] = window['__styled-components-init__'] || 0;

```

And that's what caused the error to us at the time. On v5.1.1, there was a `typeof window` guard, but from v5.2 on it seems like this guard was removed?

**Comment by wagoid** [comment]
To go deeper on this: this only breaks projects that were using the browser bundle on the server side.
Was the library's intention to support that before? If yes, then I believe this was a breaking change since the library stopped checking for `typeof window` at runtime. If not, then it would be just about updating the projects with this issue to correctly load the server bundle on its server build 😃
