### ISSUE TITLE
Provide `styled` as a named export

### ISSUE THREAD

**Issue by JacobLey** [styled-components/styled-components#3437]
Currently `styled` is only available as the default export: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/index.js#L5

In transpiled/commonJS environments that works as expected, but breaks server-side ESM usage of styled components.

NodeJS does not support CommonJS modules have _both_ a default and a named export: https://nodejs.org/api/esm.html#esm_import_statements

So for styled components to work server side instead of:
```
import styled from 'styled-components';
```

We must write:
```
import styledWrapper from 'styled-components';
styled = styledWrapper.default;
```
Which is confusing, and not a viable option for code that should run in both browser and server.

Adding `styled` as a named export allows environment agnostic access:
```
import { styled } from 'styled-components';
```

Happy to open a PR, should be a one liner.
But wanted to explain reasoning as well

**Comment by kitten** [comment]
We already have an ESM build so I don't see why the solution would be to provide a redundant export rather than to add the `"exports"` field to the `package.json` 🤔

**Comment by JacobLey** [comment]
The `exports` field IMHO is great for things like restricting what files can be imported, and changing behavior based on node/browser environments.
While it does support ESM vs CJS importing, that would actually break things further (in my case).

My use case is I use styled components in a NextJS environment. NextJS uses CJS internally, so there is nothing I can do to force them to import ESM version. My code however is pure ESM (I have a custom Webpack which stops NextJS from its usual CJS transpiling), which would result in an ESM import.
That would mean two different versions of styled-components would get imported into every project, with all the headaches that come along with that.

Being able to always import the CJS version is the best way to ensure I only get one version of styled-components, but then run into the issue described in this ticket

**Comment by brandonryan** [comment]
This is also a problem when trying to import /native

**Comment by kitten** [comment]
@JacobLey I think you misunderstood me, sorry for the confusion. Default exports are a thing. Next.js uses Webpack and does enable support of ESM, so I'm not sure what's going on here. However, adding a redundant export won't resolve the underlying issue you're probably experiencing here. But without details of the underlying issue, I can't really pin down what's going on here.

So, in other words, given that I don't think it makes sense to do this, and without another course of action, I'll have to close this, sorry!

**Comment by JacobLey** [comment]
Next.js does not use ESM. It uses webpack to transform ESM compliant code into CJS. Which is nice if you go all in on NextJS + CJS, but that is not my case. I want to continue using _actual_ ESM where possible.

The final (transpiled and simplified) code for styled-components looks something like:
```
'use strict';
exports._esModule = true;
const css = () => {...};
const styled = () => {...};
exports.css = css;
exports.default = styled;
```

CJS does not actually have a concept of a "default" export. It simply flags the module as `_esModule` compatible, and libraries like Webpack synthetically detect that the CJS code can be used as if ESM.

If you look in a transpiled module, you will see `import styled from 'styled-compnents'` replaced by something like:
```
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const { default: styled } = _interopRequireDefault(require("styled-components"));
```
This is the kind of code bundlers like Webpack inject into your code in order to simulate ESM support.

When I access styled-components from an ESM module (that is actually running ESM, not webpack transpiled CJS) that `styled` variable is now the entire exported module, not the specific `styled` method. Running into the issue described in this issue.

Because of the way NodeJS imports work https://nodejs.org/api/esm.html#esm_import_statements named exports are actually fully supported between CJS and ESM (assuming the CJS package is properly transpiled with `exports._esModule = true`). Hence adding `styled` to named exports would be a quick and easy way to resolve this issue.

Perhaps a better way for you to understand is try it yourself.

Create a directory with `package.json`:
```
{ "type": "module" }
```
Then a file `styled-fail.js` with content:
```
import styled from 'styled-components';

export const foo = styled.div`
   display: block;
`;
```
And a file `styled-success.js` with content:
```
import styled from 'styled-components';

export const foo = styled.default.div`
   display: block;
`;
```

In your repl, run the commands:
```
import('./styled-fail.js').catch(console.log); // Will print error message saying `div is not a function`
import('./styled-success.js').then(console.log); // Will print module with `foo` export
```

**Comment by JacobLey** [comment]
So summary:

* My code is written and **executed** as ESM
* styled-components is **written** as ESM but **executed** as CJS
* An ESM-executable version exists, but it is tricky to force all consumers of styled-components to use same exact module (different imports in same environment is anti-pattern)
* named exports is fully supported in _all of_ CJS->ESM, CJS->CJS, and ESM->ESM import
* default exports is only supported in ESM->ESM import. Libraries like Webpack simulate this functionality for CJS->CJS import.
* In order to fully support CJS->ESM, do not do anti-pattern of default exports OR conditional exports. Rather add method as named export.

I would like to see this issue re-opened because the problem still exists. It sounds like there is confusion about what is natively supported by ESM+NodeJS, and what requires a transpiler like Webpack

**Comment by kitten** [comment]
it's not possible to currently convert any libraries to be ESM-native modules, with all that's involved however, if they use React, which isn't ESM-native. You can try that yourself, but I also maintain `urql` which explicitly can't use native-ESM on its React bindings package because of this.

**Comment by JacobLey** [comment]
I am not trying to make the `styled-components` library an ESM-native module. I am totally fine with it using CJS for maximum compatibility.

However the way it mixes named and default exports makes it incompatible with ESM native packages.

I am not sure I follow why React is a blocker to being ESM native? A package can use ESM while simultaneously using CJS packages (that is by design, so all CJS->ESM is backwards compatible, it is the opposite ESM->CJS that is not possible without the async `import()` command). And thanks to the [JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) React avoids any default import problems described in this issue.

I personally use server-side React to render email templates in an ESM environment and it works just fine.

**Comment by karol-f** [comment]
Current temporary workaround is to create own `styled-components` file exporting `styled` in a good way:

```
import styled from 'styled-components';

export * from 'styled-components';

const defaultStyled = typeof styled === 'function' ? styled : styled.default;

export { defaultStyled as default };

```

Then you either:
* change imports from `import styled from 'styled-components'` to `import styled, { css } from './my-styled-components'`
* or if you don't use webpack externals for `styled-components` just use alias to make it tansparent for other devs, without changing imports

**Comment by machineghost** [comment]
Thank you Karol-f for that great workaround, but Stylerd Components maintainers ... why are you fighting so hard against this?  You're literally making life more difficult for a number of engineers all to avoid ... what?  One extra export line?

**Comment by lynndylanhurley** [comment]
@karol-f thank you so much. Your approach resolved the issue I was having trying to bundle styled-components into an npm module.

This issue really should be resolved, or at the very least @karol-f's comment should be in the main FAQ.

**Comment by dexbol** [comment]
It's 2023 now. Native ES module is more popular. Shall we reopen it?

**Comment by jonaskello** [comment]
> It supported in v6.0.0-beta.7

Still it would be nice to have this backported.

**Comment by joselmarianocreateape** [comment]
Hi guys, I'm using Version 6.0.7, and I still encounter this issue, I'm wondering if there's additional configuration needed for this to make it work.

Thank you in advance

**Comment by shlokamin** [comment]
i'm experiencing the same issue. i've got a components library that uses styled-components which I bundle using vite into CJS. the components library then gets imported into an external Next JS app. my bundled components library code looks like this:

```js
R=require("styled-components")
R.div.withConfig(...)
```

I get an error (`Type Error: Cannot read property 'withConfig' of undefined`) from that second line because `div` is inside of a `default` key. i appreciate [the workaround above](https://github.com/styled-components/styled-components/issues/3437#issuecomment-1103085056) but is there any official response/suggestion from the styled-components maintainers? I'd really rather not add cruft/confusion into my org to accommodate this issue.
