### ISSUE TITLE
Chrome 129 caused some of styled components to have missing styles

### ISSUE THREAD

**Issue by slavik-chapelskyi** [styled-components/styled-components#4351]
## System:
 - OS: macOS 14.1.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 84.19 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
 - Yarn: 1.22.22 - ~/.yarn/bin/yarn
 - npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
 - pnpm: 7.9.5 - ~/Library/pnpm/pnpm
## npmPackages:
 - styled-components: 6.1.0 => 6.1.0 

## Reproduction

I couldn't provide the reproduction code or repo in on codesandbox with a simple setup. This might happen due to how the our app behaves

## Steps to reproduce
After upgrading to Chrome 129, some of our users have started reporting UI glitches in parts of our application. We use Next.js 14.1.1 with styled-components v6, serving it as a static export and through AWS CloudFront. Many of our applications using the same setup have begun experiencing random UI glitches with missing styles. The issue does not occur in other browsers like Safari, Firefox, or earlier versions of Chrome. The classnames are present some of style rules are missing so part of UI are not properly displayed

Most of the time, the UI loads incorrectly. Refreshing the page multiple times sometimes results in the UI displaying correctly. (very rare cases, maybe 1 of 20-30 times it loads fine)

A somewhat random fix was to add `<StyleSheetManager enableVendorPrefixes>`, which almost resolved the issue. Now, the problem occurs approximately 1 out of every 20 times, whereas before, it loaded correctly more consistently.

![CleanShot 2024-09-19 at 14 26 46@2x](https://github.com/user-attachments/assets/867f1b50-3dcd-4803-bb96-367dd2607fd8)

**Comment by andreyfmc** [comment]
I think this will help you.
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by pcunha29** [comment]
I'm facing the same scenario but with `Next.js 13` 

Have you managed to find a solution so far?

**Comment by pcunha29** [comment]
UPDATE: Adding `disableCSSOMInjection` into `<StyleSheetManager` seems to help a bit. Not a perfect solution, but the best we found so far.

**Comment by duch0416** [comment]
@pcunha29 seems with enableVendorPrefixes it behaves better

**Comment by silasb** [comment]
See https://issues.chromium.org/issues/367758074

Try running with:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --js-flags=--no-maglev-optimistic-peeled-loops
```

To see if it helps.

**Comment by OlesZadorozhnyy** [comment]
> See https://issues.chromium.org/issues/367758074
> 
> Try running with:
> 
> ```
> /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --js-flags=--no-maglev-optimistic-peeled-loops
> ```
> 
> To see if it helps.

Yeah, it resolves the issue!

**Comment by pcunha29** [comment]
> See https://issues.chromium.org/issues/367758074
> 
> 
> 
> Try running with:
> 
> 
> 
> ```
> 
> /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --js-flags=--no-maglev-optimistic-peeled-loops
> 
> ```
> 
> 
> 
> To see if it helps.

It works! Thank you! 🙏

**Comment by maghidini** [comment]
See https://issues.chromium.org/issues/367758074 :)

**Comment by rafael-sales-brisa** [comment]
i have the same problem using material-ui v 5 with next.js 13.4.5, im using pages router, my style is breaking :/

**Comment by karol-f** [comment]
For styled components to fix issue please use `SC_ATTR` - https://styled-components.com/docs/advanced#avoiding-conflicts-with-third-party-styles-and-scripts

**Comment by redapy** [comment]
we are facing the same issue, but only in production (Chrome 129).  Possibly related to hydration.

Here is a [minimal reproduction](https://github.com/redapy/next-twin/blob/main/src/app/page.tsx) (PS: I'm using twin.macro)

**Comment by kirand51** [comment]
issue it still present in Edge browser with same 129 version. @marwanKettleCom 
fixed in chrome

**Comment by ethanryan** [comment]
issue is fixed for us in latest version of Chrome:

Version 129.0.6668.71

**Comment by DVHuan** [comment]
so anyone know what is the root cause? I got UI error for only one page.

**Comment by rcantin-w** [comment]
We had this in September as well, and since the new Chrome it's back. `131.0.6778.70 (Official Build) (arm64)`

I wrote in the [Chromium issues platform](https://issues.chromium.org/issues/367758074#comment41), however as this seems particular to styled-components, I'm wondering if this could be investigated from this side as well?

**Comment by Mario34** [comment]
The problem mainly occurs in browsers with the Chromium core.
Chrome 131.0.6778.86
Edge 131.0.2903.86

After upgrading Chrome to version 131.0.6778.109, the problem no longer occurs.
As of now, the latest version of Edge 131.0.2903.86 is still not fixed.
Hope it is helpful to everyone.

**Comment by quantizor** [comment]
Closing — this was caused by a V8 Maglev JIT compiler bug in Chrome 129 (https://issues.chromium.org/issues/367758074), fixed by the Chrome team. The `GroupedTag.indexOfGroup` loop was being miscompiled by Maglev's "optimistic peeled loops" optimization, causing rules to be inserted at wrong positions.

If you encounter similar CSSOM-related browser issues in the future, `<StyleSheetManager disableCSSOMInjection>` can be used as a workaround.
