### ISSUE TITLE
styled-components + native-base causing an error

### ISSUE THREAD

**Issue by yaronlevi** [styled-components/styled-components#645]
Hi! I am having problems using styled-components + native-base.
When I try to style a native-base's button like so:

```JS
const StyledButton = styled(Button)`margin:10;`
```

I get an error: "Faild prop type: Invalid props.style key '0' supplied to View"
This happens for any native-base component that I use.
Am I doing somethink wrong here?

**Comment by mxstbr** [comment]
You need to use backticks rather than single quotes:

```JS
const StyledButton = styled(Button)`
  margin: 10;
`
```

That's because `styled-components` uses [ES6 tagged template literals](http://mxstbr.blog/2016/11/styled-components-magic-explained/). Let me know if that solves the issue!

**Comment by yaronlevi** [comment]
(-: I did used backticks I my code. I just removed them here so they won't interfere with markdown.

**Comment by yaronlevi** [comment]
And versions are:
styled-components@1.4.4
native-base@2.0.13
react-native@0.42.3

**Comment by JDansercoer** [comment]
Yeah, I'm getting

`Failed prop type: Invalid prop `style` of type `array` supplied to `Styled(Button)`, expected `object`.`

**Comment by philpl** [comment]
We're just passing the `style` prop. This error says that one item in a `style={[]}` array in the JSX contains a key `0`, which indicates that an array is passed in. So it sounds like it's somehow assembling `style={[ [] ]}` or sth similar.

What is that `Button` component you two are referring to? Can you post a link? And maybe also a reproduction if you have time? Without I have to assume that it's not an SC issue, since it's a `prop` error, which means it's above or below SC.

**Comment by Charlynux** [comment]
Button component comes from NativeBase project.

Here is the source code :
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Button.js

If needed, I can push a small repo with reproduction.

**Comment by philpl** [comment]
@Charlynux I'd bet that there's a problem with https://github.com/GeekyAnts/NativeBase/blob/master/src/Utils/computeProps.js

Can you open an issue over at NativeBase and see what they can say about this? I'm not even aware of what this `computeProps` method is trying to do. Merging props shouldn't require a single object, but an array should do it.

**Comment by mxstbr** [comment]
Reference issue: https://github.com/GeekyAnts/NativeBase/issues/575

Since this seems to be an issue with NativeBase and not styled-components I'll close this issue for now. Thanks for helping us make the library more compatible!

**Comment by marcellkiss** [comment]
The referenced issue was closed, saying it's solved in 2.3.0. I'm using this version, and styled doesn't take any effect on a native-base button

**Comment by swaroopa94** [comment]
Hi I also tried like this : 

```
import styled from 'styled-components/native';
const NavbarRightView = styled.Segmeny`
  width : $(width/2);
`
```

Its throwing error  and Segment is nativebase compopnents
How to solve this error

**Comment by swaroopa94** [comment]
@Charlynux  Thank you its working now

**Comment by LucianBuzzo** [comment]
@swaroopa94 Was the problem caused by the typo?

**Comment by smakosh** [comment]
I tried what @Charlynux suggested but it still doesn't work :/
