### ISSUE TITLE
Targeting styled components with enzyme's .find()

### ISSUE THREAD

**Issue by three60five** [styled-components/styled-components#896]
When I use styled-components to make "building block" components defined in the same file as the "assembled" component, I am having a really difficult time targeting them in my tests using enzyme's `.find()` method. 

For example, with this styled-component:
```
import ImportedComponent from './ImportedComponent';
const Demo = styled.div`
`;
const Label = styled.span`
`;
const Thing = () =>
  <Demo>
    <ImportedComponent />
    <Label />
    <Label /> 
    <Label />
  </Demo>;
```
If I use an imported styled-component like `<ImportedComponent>`, I can easily find it like with enzyme like: 
```
describe('<Thing />', () => {
  it('should contain an ImportedComponent', () => {
    const wrapper = shallow(<Thing />);
    const importedComponent = wrapper.find('ImportedComponent');
    expect(importedComponent).to.have.length(1);
  });
});
```
But I haven't found an elegant way to find the "building block" components like `<Label />` because they can't be found by the component name as they appear more generically like "<styled.span>". Is there a way for these "building block" components to appear with their component name like they are when imported? I don't want to resort to targeting them by html or css as that is more brittle.

**Comment by mxstbr** [comment]
Please chime in here! #624

**Comment by foiseworth** [comment]
@three60five did your issue get resolved in the other thread? I can't see an answer to it and I'm tackling the same issue.

**Comment by bteng22** [comment]
bump! Also running into this problem that doesn't seem to be resolved in issue #624 

```
const wrapper = mount(
  <MyComponent {...props} />
)

console.log(wrapper.debug())
/* Returns
<div>
  <styled.li active={true}>
    <li className="sc-htoDjs jVFisz" ref={[undefined]}>
    </li>
  </styled.li>
</div>
*/

console.log(wrapper.find('styled.li').debug()) // This line doesn't find a node!!
```
Trying to select the styled.li component to assert that the attribute active gets set appropriately from props and it doesn't seem to be cooperating too well. 

(using preact, which hopefully, doesn't contribute to the problem)
Versions:
```
"enzyme": "^2.9.1",
"jest": "^20.0.4",
"preact-compat-enzyme": "^0.2.5",
"preact-test-utils": "^0.1.3",
```

**Comment by philpl** [comment]
You can always set the displayName manually to discover a certain component.

Afaik you can also pass the component into find to discover it instead of a display name

Maybe you could help to propose a helper for this kind of functionality on jest-styled-components? https://github.com/styled-components/jest-styled-components/issues/61

**Comment by camsjams** [comment]
> You can always set the displayName manually to discover a certain component.
This does work, but makes clunky exports all over the place.

In reference to OP situation (which was not resolved on #624 which is heavily focused on theme testing), are there any alternatives to exporting all of our "building block" styled components?

**Comment by camsjams** [comment]
Another alternative is to override the default styled components `displayName`:

```
const MessageText = styled.span`
	& {
		font-weight: bold;
	}
`;

MessageText.displayName = 'MessageText';
```

And then in testing:
`t.equals(wrapper.find('MessageText').children().text(), 'Some expected Message');`

**Comment by three60five** [comment]
I use the `babel-plugin-styled-components` package now to automatically create the displayName. This makes finding the building block components the same as imported, but to find the name of the component you must look in your React DevTools.

**Comment by guidosreis** [comment]
@kitten and @camsjams Thanks a lot!

**Comment by ahahn95** [comment]
@three60five How did you get this to work for testing? I use CRA, react-app-rewired, and rewireStyledComponents. On my react dev tools, it is working, but when I use .debug() from enzyme, the regular <styled.div> etc is showed.

**Comment by ahahn95** [comment]
@three60five Yes, but unfortunately I don't have access to my webpack config and am not in a position to eject, thus react-app-rewired.

**Comment by three60five** [comment]
@ahahn95 the Babel plugin doesn’t require any webpack changes.

**Comment by jessepinho** [comment]
For future readers, you don't need to use text to find a styled component. You can simply import the styled component itself to find it. Modifying the original example to do this:

```JavaScript
// Thing.jsx

import ImportedComponent from './ImportedComponent';

const Demo = styled.div`
`;

// Note that this is exported (I personally prefer to put styles in a separate `styles.ts` file)
export const Label = styled.span` 
`;

const Thing = () =>
  <Demo>
    <ImportedComponent />
    <Label />
    <Label /> 
    <Label />
  </Demo>;

export default Thing;

// Thing.test.jsx

import Thing, { Label } from './Thing';

describe('<Thing />', () => {
  it('should contain a Label', () => {
    const wrapper = shallow(<Thing />);
    const label = wrapper.find(Label);
    expect(label).to.have.length(1);
  });
});
```

**Comment by Bielousov** [comment]
In my case the following approach seems to be working:
```
const label = wrapper.dive().find('label');
expect(label).to.have.length(1);
```
